Feature/add devise
ClaudiaRojasSoto/Blog_App pull request #9
Opened 2023-10-04 17:51 UTC by ClaudiaRojasSoto

## Add Devise for User Authentication

### Description
This pull request adds the Devise gem to the application to manage user registration and authentication. Devise provides a flexible and secure way to handle user accounts. This ensures that users can register, confirm their emails, and reset their passwords.

### General Requirements
- [x] No linter errors
- [x] Used correct Gitflow
- [x] Work is well-documented

### Ruby Requirements
- Followed all best practices for Ruby as per guidelines.

### Project Requirements
- [x] Removed `current_user` method from `ApplicationController` as Devise provides one.
- [x] Installed and set up Devise.
- [x] Users can register a new account.
- [x] Users can log in with a combination of email and password.
- [x] Hashed passwords are being stored in the database.
- [x] Email confirmation upon registration.
- [x] Users can reset their passwords.
- [x] Modified Devise views for registration and login to match the wireframes and styling.

### How to Test
1. Clone the feature branch into your local machine.
2. Run `bundle install` to install the Devise gem.
3. Run `rails db:migrate` to apply the new Devise-related database migrations.
4. Start the Rails server.
5. Go to the registration and login pages to check if they match the wireframes and your styling.

Please, review the changes made on this feature and give me feedback to improve my app. Thank you in advance.

### Contributors
@ClaudiaRojasSoto 
@Dachrono

2023-10-04 20:02 UTC, Felix45 requested changes
Hi @ClaudiaRojasSoto  & @Dachrono , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://camo.githubusercontent.com/59fa9d95c18dbd5a8e47490a9e4b48393f569685410f3c78d4d83a9764fa1392/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Devise gem is used for authentication  :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:   


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 20:02 UTC, Felix45 commented on app/views/devise/registrations/new.html.erb
> +<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'post-form' }) do |f| %>
- [ Required ] I think it would be nice if you make the `registration` form work as expected, currently, when I fill in all the fields and click on the `Sign Up` button I get the error below. Please see the screenshot below and rectify this.

## Screenshot
> I get this error even after filing the `name` field, kindly rectify this.

![Screenshot from 2023-10-04 22-22-41](https://github.com/ClaudiaRojasSoto/Blog_App/assets/16392046/b69aabbd-b488-456a-ba3d-6b91908efd3b)

2023-10-04 20:02 UTC, Felix45 commented on app/views/devise/sessions/new.html.erb
> +<% end %>
- [ Required ] I think it would be nice if the design for your login form is consistent with the wireframe provided for this milestone. Currently, your design varies from the wireframe in the following ways.
   
   - In the wireframe, the `username`, `password`, and `login` buttons have the same width while in your design the fields have varied lengths.
   - The `username` and `password` fields in the wireframe have placeholder text while the `input` fields in your design don't have placeholder texts.

## Your design
![Screenshot from 2023-10-04 22-26-12](https://github.com/ClaudiaRojasSoto/Blog_App/assets/16392046/bf7928e0-4392-4ebc-b2b4-116b30a31d27)


## Project Wireframe
![](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_login.png)

2023-10-04 20:02 UTC, Felix45 commented on app/views/devise/registrations/new.html.erb
> +<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'post-form' }) do |f| %>
- [ Required ] I think it would be nice if your design for the `registration` form is similar to the one provided for the `Sign In` form in the project wireframe. Currently, your design varies from the wireframe in the following ways.
   
   - In the wireframe, the `name`, `email`, `password`, and `login` buttons have the same width while in your design the fields have varied lengths.
   - The `input` fields in the wireframe have placeholder text while the `input` fields in your design don't have placeholder text.

## Your design
![Screenshot from 2023-10-04 22-51-37](https://github.com/ClaudiaRojasSoto/Blog_App/assets/16392046/25ce8754-198e-49f2-beb1-794a7bcd1be6)

## Project wireframe
![](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_login.png)

2023-10-04 20:52 UTC, ClaudiaRojasSoto commented on app/views/devise/registrations/new.html.erb
> +<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'post-form' }) do |f| %>
Done!, Thank you.

2023-10-04 20:53 UTC, ClaudiaRojasSoto commented on app/views/devise/sessions/new.html.erb
> +<% end %>
Done!, Thank you.

2023-10-04 20:53 UTC, ClaudiaRojasSoto commented on app/views/devise/registrations/new.html.erb
> +<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'post-form' }) do |f| %>
Done, Thank you.

2023-10-05 01:00 UTC, AmaduKamara approved these changes
# Status: Approved 🟢 🟢 🟢

Hi @ClaudiaRojasSoto,

Good job working on the changes highlighted by the previous reviewer 👍🏽

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ You set up Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ Used devise correctly as expected 👍🏽
✅ Sign up and Login UI designed nicely as expected 👍🏽
✅ Good communication with the reviewer 👍🏽
✅ Good descriptive PR and commit messages 👍🏽

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-10-05 12:41 UTC, merged